[windows.mcp_servers.supabase]
url = "https://server.smithery.ai/supabase/mcp"
env_http_headers = { "SMITHERY_PROFILE" = "SMITHERY_PROFILE", "SMITHERY_API_KEY" = "SMITHERY_API_KEY" }

[windows.mcp_servers.ref]
command = "npx.cmd"
args = ["-y", "ref-tools-mcp"]

[windows.mcp_servers.exa]
url = "https://server.smithery.ai/exa/mcp"
env_http_headers = { "SMITHERY_PROFILE" = "SMITHERY_PROFILE", "SMITHERY_API_KEY" = "SMITHERY_API_KEY" }

[windows.mcp_servers.sequential-thinking]
url = "https://server.smithery.ai/@smithery-ai/server-sequential-thinking/mcp"

[windows.mcp_servers.browserbase]
url = "https://server.smithery.ai/@browserbasehq/mcp-browserbase/mcp"
env_http_headers = { "SMITHERY_PROFILE" = "SMITHERY_PROFILE", "SMITHERY_API_KEY" = "SMITHERY_API_KEY" }

[windows.mcp_servers.notion]
url = "https://server.smithery.ai/notion/mcp"
env_http_headers = { "SMITHERY_PROFILE" = "SMITHERY_PROFILE", "SMITHERY_API_KEY" = "SMITHERY_API_KEY" }

[windows.mcp_servers.clear-thought-mcp]
command = "npx.cmd"
args = ["-y", "@smithery/cli@latest", "run", "@ThinkFar/clear-thought-mcp"]
env = { "SMITHERY_API_KEY" = "SMITHERY_API_KEY" }

[windows.mcp_servers.gmail-mcp]
command = "npx.cmd"
args = ["-y", "@smithery/cli@latest", "run", "@shinzo-labs/gmail-mcp"]
env = { "SMITHERY_API_KEY" = "SMITHERY_API_KEY", "SMITHERY_PROFILE" = "SMITHERY_PROFILE" }

[windows.mcp_servers.playwright-mcp]
command = "npx.cmd"
args = ["-y", "@smithery/cli@latest", "run", "@playwright/mcp"]
env = { "SMITHERY_API_KEY" = "SMITHERY_API_KEY" }

[windows.mcp_servers.context7]
url = "https://mcp.context7.com/mcp"

[windows.mcp_servers.serena]
url = "http://localhost:8765/sse"
startup_timeout_sec = 10

[windows.mcp_servers.zen]
command = "uvx"
args = ["--from", "git+https://github.com/BeehiveInnovations/zen-mcp-server.git", "zen-mcp-server"]

[windows.mcp_servers.playwright]
command = "npx.cmd"
args = ["-y", "@playwright/mcp"]

[windows.mcp_servers.desktop-commander]
command = "npx.cmd"
args = ["-y", "@wonderwhy-er/desktop-commander"]

[windows.mcp_servers.gemini-cli-server]
command = "gemini.cmd"
args = ["mcp", "server"]

[wsl.mcp_servers.supabase]
url = "https://server.smithery.ai/supabase/mcp"
env_http_headers = { "SMITHERY_PROFILE" = "SMITHERY_PROFILE", "SMITHERY_API_KEY" = "SMITHERY_API_KEY" }

[wsl.mcp_servers.ref]
command = "/home/matt/.nvm/versions/node/v25.2.1/bin/npx"
args = ["-y", "ref-tools-mcp"]

[wsl.mcp_servers.exa]
url = "https://server.smithery.ai/exa/mcp"
env_http_headers = { "SMITHERY_PROFILE" = "SMITHERY_PROFILE", "SMITHERY_API_KEY" = "SMITHERY_API_KEY" }

[wsl.mcp_servers.sequential-thinking]
url = "https://server.smithery.ai/@smithery-ai/server-sequential-thinking/mcp"

[wsl.mcp_servers.browserbase]
url = "https://server.smithery.ai/@browserbasehq/mcp-browserbase/mcp"
env_http_headers = { "SMITHERY_PROFILE" = "SMITHERY_PROFILE", "SMITHERY_API_KEY" = "SMITHERY_API_KEY" }

[wsl.mcp_servers.notion]
url = "https://server.smithery.ai/notion/mcp"
env_http_headers = { "SMITHERY_PROFILE" = "SMITHERY_PROFILE", "SMITHERY_API_KEY" = "SMITHERY_API_KEY" }

[wsl.mcp_servers.clear-thought-mcp]
command = "/home/matt/.nvm/versions/node/v25.2.1/bin/npx"
args = ["-y", "@smithery/cli@latest", "run", "@ThinkFar/clear-thought-mcp"]
env = { "SMITHERY_API_KEY" = "SMITHERY_API_KEY" }

[wsl.mcp_servers.gmail-mcp]
command = "/home/matt/.nvm/versions/node/v25.2.1/bin/npx"
args = ["-y", "@smithery/cli@latest", "run", "@shinzo-labs/gmail-mcp"]
env = { "SMITHERY_API_KEY" = "SMITHERY_API_KEY", "SMITHERY_PROFILE" = "SMITHERY_PROFILE" }

[wsl.mcp_servers.playwright-mcp]
command = "/home/matt/.nvm/versions/node/v25.2.1/bin/npx"
args = ["-y", "@smithery/cli@latest", "run", "@playwright/mcp"]
env = { "SMITHERY_API_KEY" = "SMITHERY_API_KEY" }

[wsl.mcp_servers.context7]
url = "https://mcp.context7.com/mcp"

[wsl.mcp_servers.serena]
url = "http://localhost:8765/sse"
startup_timeout_sec = 10

[wsl.mcp_servers.zen]
command = "/home/matt/.local/bin/uvx"
args = ["--from", "git+https://github.com/BeehiveInnovations/zen-mcp-server.git", "zen-mcp-server"]

[wsl.mcp_servers.playwright]
command = "/home/matt/.nvm/versions/node/v25.2.1/bin/npx"
args = ["-y", "@playwright/mcp"]

[wsl.mcp_servers.desktop-commander]
command = "/home/matt/.nvm/versions/node/v25.2.1/bin/npx"
args = ["-y", "@wonderwhy-er/desktop-commander"]

[wsl.mcp_servers.gemini-cli-server]
command = "/home/matt/.nvm/versions/node/v25.2.1/bin/gemini"
args = ["mcp", "server"]
